// app/layout.tsx or wherever your RootLayout is

import './globals.css';

export const metadata = {
  title: 'Capgemini Clone',
  description: 'Generated by Sourav, Sarthak',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex-row antialiased">{children}</body>
    </html>
  );
}
